# Concatenates the GPU device sources into a single MSL translation unit and
# embeds it as a C byte array (openmc_gpu_msl / openmc_gpu_msl_len) so the
# Metal backend can runtime-compile kernels with no offline toolchain.
#
# Usage:
#   cmake -DMSL_SOURCES="a.h;b.h" -DMSL_OUTPUT=out.c -P EmbedMsl.cmake

set(concat "")
foreach(f ${MSL_SOURCES})
  file(READ "${f}" chunk)
  # '#pragma once' is meaningless in the concatenated main source
  string(REPLACE "#pragma once" "" chunk "${chunk}")
  string(APPEND concat "// ==== ${f} ====\n${chunk}\n")
endforeach()

string(LENGTH "${concat}" srclen)

# hex-encode and rewrite as a C array
string(HEX "${concat}" hex)
string(REGEX REPLACE "([0-9a-f][0-9a-f])" "0x\\1," bytes "${hex}")

file(WRITE "${MSL_OUTPUT}"
  "// Generated by cmake/EmbedMsl.cmake — do not edit.\n"
  "extern const unsigned char openmc_gpu_msl[];\n"
  "extern const unsigned long openmc_gpu_msl_len;\n"
  "const unsigned char openmc_gpu_msl[] = {${bytes}0x00};\n"
  "const unsigned long openmc_gpu_msl_len = ${srclen};\n")
