//! \file runner.cpp
//! Orchestrates GPU transport generations: flatten → upload → dispatch →
//! feed results back into OpenMC's host-side (fp64) statistics pipeline.
//! Everything outside the particle flight — bank synchronization, keff
//! statistics, tally accumulation across batches, statepoints — is untouched
//! upstream code, which is what keeps GPU runs drop-in compatible.

#include "openmc/gpu_interface.h"

#include <algorithm>
#include <cmath>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <vector>

#include <fmt/format.h>

#include "openmc/bank.h"
#include "openmc/capi.h"
#include "openmc/constants.h"
#include "openmc/error.h"
#include "openmc/geometry.h"
#include "openmc/message_passing.h"
#include "openmc/mgxs_interface.h"
#include "openmc/particle_data.h"
#include "openmc/random_lcg.h"

namespace openmc {
// file-scope globals in random_lcg.cpp with external linkage
extern int64_t master_seed;
extern uint64_t prn_stride;
}
#include "openmc/settings.h"
#include "openmc/simulation.h"
#include "openmc/tallies/tally.h"

#include "backend.h"
#include "flatten.h"

// Host replay of the device transport loop for lost-particle diagnosis:
// the same single-source kernels compile for the host, and RNG streams are
// identical, so lost particles reproduce deterministically (module fastmath
// contraction differences).
#define GPU_HOST_DEBUG
#include "device/transport.h"

void gpu_host_debug_escape(const GpuGeomState* gs)
{
  std::fprintf(stderr,
    "[gpu-debug] escape-after-lattice-cross r=(%.7f %.7f %.7f) u=(%.6f %.6f "
    "%.6f) surface=%d li=(%d %d %d) cell0=%d\n",
    gs->coord[0].r.x, gs->coord[0].r.y, gs->coord[0].r.z, gs->coord[0].u.x,
    gs->coord[0].u.y, gs->coord[0].u.z, gs->surface,
    gs->coord[gs->n_coord - 1].li[0], gs->coord[gs->n_coord - 1].li[1],
    gs->coord[gs->n_coord - 1].li[2], gs->coord[0].cell);
}

void gpu_host_debug_exit(const GpuGeomState* gs, float distance, float d_coll)
{
  static int count = 0;
  if (count++ > 5)
    return;
  std::fprintf(stderr,
    "[gpu-debug] EXIT r=(%.7f %.7f %.7f) u=(%.6f %.6f %.6f) d=%.7f "
    "d_coll=%.6g bdry{d=%.7f surf=%d lvl=%d trans=(%d %d %d)} on_surf=%d "
    "ncoord=%d\n",
    gs->coord[0].r.x, gs->coord[0].r.y, gs->coord[0].r.z, gs->coord[0].u.x,
    gs->coord[0].u.y, gs->coord[0].u.z, distance, d_coll, gs->boundary.d,
    gs->boundary.surface, gs->boundary.coord_level,
    gs->boundary.lat_trans[0], gs->boundary.lat_trans[1],
    gs->boundary.lat_trans[2], gs->surface, gs->n_coord);
}

void gpu_host_debug_lost(const GpuGeomState* gs, int32_gpu tok, GpuVec3 r0,
  GpuVec3 u0, GpuVec3 u_new)
{
  std::fprintf(stderr,
    "[gpu-debug] reflect-lost tok=%d r=(%.7f %.7f %.7f) u_in=(%.6f %.6f "
    "%.6f) u_out=(%.6f %.6f %.6f) ncoord=%d cell0=%d\n",
    tok, r0.x, r0.y, r0.z, u0.x, u0.y, u0.z, u_new.x, u_new.y, u_new.z,
    gs->n_coord, gs->coord[0].cell);
}

extern "C" {
// generated by cmake/EmbedMsl.cmake from src/gpu/device/*.h
extern const unsigned char openmc_gpu_msl[];
extern const unsigned long openmc_gpu_msl_len;
}

namespace openmc {
namespace gpu {

namespace {

struct Engine {
  void* ctx = nullptr;
  FlatModel flat;
  bool active = false;
  std::string reason;
  double gpu_seconds = 0.0;
  int64_t lost_total = 0;
  uint32_t n_red_slots = 0;
};

Engine eng;

int overall_generation_()
{
  return settings::gen_per_batch * (simulation::current_batch - 1) +
         simulation::current_gen;
}

bool fail(std::string why)
{
  eng.reason = std::move(why);
  if (eng.ctx) {
    omg_metal_destroy(eng.ctx);
    eng.ctx = nullptr;
  }
  eng.active = false;
  warning(fmt::format(
    "GPU transport disabled — {}. Running on the CPU instead.", eng.reason));
  return false;
}

template<typename T>
bool upload(int slot, const std::vector<T>& v)
{
  size_t bytes = v.size() * sizeof(T);
  if (omg_metal_buffer(eng.ctx, slot, bytes))
    return false;
  if (!v.empty())
    std::memcpy(omg_metal_contents(eng.ctx, slot), v.data(), bytes);
  return true;
}

//! Verify the device PRN generator is integer-identical to the host's.
bool rng_selftest()
{
  const int N = 64;
  std::vector<uint64_t> io(4 * N);
  for (int i = 0; i < N; ++i) {
    io[4 * i] = 0x9e3779b97f4a7c15ull * (uint64_t)(i + 1) + 12345ull;
    io[4 * i + 1] = 1000 + 17 * (uint64_t)i;
  }
  if (omg_metal_buffer(eng.ctx, 0, io.size() * 8))
    return false;
  std::memcpy(omg_metal_contents(eng.ctx, 0), io.data(), io.size() * 8);
  char err[512];
  if (omg_metal_dispatch(eng.ctx, "openmc_rng_selftest", N, err, sizeof(err)))
    return false;
  auto* out = static_cast<uint64_t*>(omg_metal_contents(eng.ctx, 0));
  for (int i = 0; i < N; ++i) {
    uint64_t seed = io[4 * i];
    uint64_t n = io[4 * i + 1];
    uint64_t word = 0;
    uint64_t host_seed = seed;
    double last = 0.0;
    for (uint64_t k = 0; k < n; ++k)
      last = prn(&host_seed);
    // recompute the output word with the host-compiled device generator
    uint64_t s2 = seed;
    for (uint64_t k = 0; k < n; ++k) {
      uint64_t tmp = s2;
      word = gpu_prn_word(&tmp);
      s2 = tmp;
    }
    if (out[4 * i + 3] != host_seed || out[4 * i + 3] != s2 ||
        out[4 * i + 2] != word ||
        std::abs(std::ldexp((double)word, -64) - last) > 1e-15) {
      return false;
    }
  }
  return true;
}

} // namespace

const std::string& inactive_reason()
{
  return eng.reason;
}

bool active()
{
  return eng.active;
}

void try_initialize()
{
  if (!settings::gpu)
    return;
  if (eng.active)
    return;

#ifdef OPENMC_USE_MPI
  if (mpi::n_procs > 1) {
    fail("MPI runs are not in the GPU v1 envelope");
    return;
  }
#endif
  if (settings::run_mode != RunMode::EIGENVALUE) {
    fail("only eigenvalue runs are in the GPU v1 envelope");
    return;
  }
  if (simulation::work_per_rank > 0x7fffffffLL) {
    fail("more than 2^31 particles per generation");
    return;
  }
  if (!omg_metal_available()) {
    fail("no Metal device available");
    return;
  }

  if (!flatten_model(eng.flat)) {
    fail(eng.flat.reject_reason);
    return;
  }

  eng.ctx = omg_metal_create();
  if (!eng.ctx) {
    fail("could not create Metal context");
    return;
  }

  // compile device source
  std::string src(reinterpret_cast<const char*>(openmc_gpu_msl),
    (size_t)openmc_gpu_msl_len);
  char err[4096];
  if (omg_metal_compile(eng.ctx, src.c_str(), err, sizeof(err))) {
    fail(fmt::format("device kernel compilation failed: {}", err));
    return;
  }

  if (!rng_selftest()) {
    fail("device RNG failed the bit-exactness self-test");
    return;
  }

  // static data upload
  if (!upload(OMG_SLOT_SURFACES, eng.flat.surfaces) ||
      !upload(OMG_SLOT_CELLS, eng.flat.cells) ||
      !upload(OMG_SLOT_UNIVERSES, eng.flat.universes) ||
      !upload(OMG_SLOT_LATTICES, eng.flat.lattices) ||
      !upload(OMG_SLOT_MATERIALS, eng.flat.materials) ||
      !upload(OMG_SLOT_MGMATS, eng.flat.mgmats) ||
      !upload(OMG_SLOT_I32, eng.flat.i32) ||
      !upload(OMG_SLOT_F32, eng.flat.f32) ||
      !upload(OMG_SLOT_TALLIES, eng.flat.tallies) ||
      !upload(OMG_SLOT_FILTERS, eng.flat.filters) ||
      !upload(OMG_SLOT_MESHES, eng.flat.meshes)) {
    fail("device buffer allocation failed");
    return;
  }

  // dynamic buffers
  int64_t n = simulation::work_per_rank;
  eng.n_red_slots = (uint32_t)((n + 255) / 256);
  int64_t bank_cap = 3 * n;
  if (omg_metal_buffer(eng.ctx, OMG_SLOT_CONTROL, sizeof(GpuControl)) ||
      omg_metal_buffer(
        eng.ctx, OMG_SLOT_SOURCE, (size_t)n * sizeof(GpuSourceSite)) ||
      omg_metal_buffer(
        eng.ctx, OMG_SLOT_FISSION, (size_t)bank_cap * sizeof(GpuSourceSite)) ||
      omg_metal_buffer(
        eng.ctx, OMG_SLOT_COUNTERS, GPU_CTR_COUNT * sizeof(uint32_t)) ||
      omg_metal_buffer(eng.ctx, OMG_SLOT_PROGENY, (size_t)n * 4) ||
      omg_metal_buffer(eng.ctx, OMG_SLOT_REDSLOTS,
        (size_t)eng.n_red_slots * GPU_RED_WIDTH * 4) ||
      omg_metal_buffer(eng.ctx, OMG_SLOT_TACCUM,
        std::max<size_t>(1, eng.flat.tally_accum_size) * 4)) {
    fail("device bank allocation failed");
    return;
  }

  eng.active = true;
  eng.reason.clear();
  write_message(
    fmt::format("GPU transport engine active on {} ({} surfaces, {} cells, "
                "{} materials, {} tallies flattened)",
      omg_metal_device_name(eng.ctx), eng.flat.surfaces.size(),
      eng.flat.cells.size(), eng.flat.mgmats.size(),
      eng.flat.tallies.size()),
    5);
}

void transport_generation()
{
  int64_t n = simulation::work_per_rank;

  // ---- control block ----
  auto* ctl = static_cast<GpuControl*>(
    omg_metal_contents(eng.ctx, OMG_SLOT_CONTROL));
  std::memset(ctl, 0, sizeof(GpuControl));
  ctl->n_particles = (uint32_t)n;
  ctl->source_offset = 0;
  ctl->run_mode = GPU_RUN_EIGENVALUE;
  ctl->energy_mode = GPU_MODE_MG;
  ctl->keff = (float)simulation::keff;
  ctl->n_groups = (uint32_t)data::mg.num_energy_groups_;
  ctl->max_events = (uint32_t)std::min<int64_t>(
    settings::max_particle_events, 0x7fffffff);
  ctl->seed_base = (uint64_t)((simulation::total_gen +
                                (int64_t)overall_generation_() - 1) *
                              settings::n_particles);
  ctl->master_seed = (uint64_t)openmc::master_seed;
  ctl->prn_stride = openmc::prn_stride;
  ctl->fission_bank_cap = (uint32_t)(3 * n);
  ctl->root_universe = model::root_universe;
  ctl->n_coord_levels = model::n_coord_levels;
  ctl->n_cells = (uint32_t)eng.flat.cells.size();
  ctl->n_surfaces = (uint32_t)eng.flat.surfaces.size();
  ctl->mg_bin_avg_off = eng.flat.mg_bin_avg_off;

  // active tallies only (device scores every desc it is told about)
  bool tallies_active = false;
  for (const auto& t : model::tallies)
    if (t->active_) {
      tallies_active = true;
      break;
    }
  ctl->n_tallies = tallies_active ? (uint32_t)eng.flat.tallies.size() : 0;

  // ---- source upload (fp64 -> fp32) ----
  auto* src = static_cast<GpuSourceSite*>(
    omg_metal_contents(eng.ctx, OMG_SLOT_SOURCE));
  double src_weight = 0.0;
  for (int64_t i = 0; i < n; ++i) {
    const SourceSite& s = simulation::source_bank[i];
    GpuSourceSite& g = src[i];
    g.r[0] = (float)s.r.x;
    g.r[1] = (float)s.r.y;
    g.r[2] = (float)s.r.z;
    g.u[0] = (float)s.u.x;
    g.u[1] = (float)s.u.y;
    g.u[2] = (float)s.u.z;
    g.E = (float)s.E;
    g.time = (float)s.time;
    g.wgt = (float)s.wgt;
    g.delayed_group = s.delayed_group;
    g.parent_id = 0;
    g.progeny_id = 0;
    src_weight += s.wgt;
  }
  simulation::total_weight += src_weight;

  // ---- zero per-generation accumulators ----
  std::memset(omg_metal_contents(eng.ctx, OMG_SLOT_COUNTERS), 0,
    GPU_CTR_COUNT * sizeof(uint32_t));
  std::memset(omg_metal_contents(eng.ctx, OMG_SLOT_PROGENY), 0, (size_t)n * 4);
  std::memset(omg_metal_contents(eng.ctx, OMG_SLOT_REDSLOTS), 0,
    (size_t)eng.n_red_slots * GPU_RED_WIDTH * 4);
  if (eng.flat.tally_accum_size > 0)
    std::memset(omg_metal_contents(eng.ctx, OMG_SLOT_TACCUM), 0,
      (size_t)eng.flat.tally_accum_size * 4);

  // ---- optional host replay for lost-particle diagnosis ----
  if (std::getenv("OPENMC_GPU_REPLAY")) {
    GpuGeomData geom;
    geom.surfaces = eng.flat.surfaces.data();
    geom.cells = eng.flat.cells.data();
    geom.universes = eng.flat.universes.data();
    geom.lattices = eng.flat.lattices.data();
    geom.i32 = eng.flat.i32.data();
    geom.f32 = eng.flat.f32.data();
    GpuMgView mgv;
    mgv.mats = eng.flat.mgmats.data();
    mgv.i32 = eng.flat.i32.data();
    mgv.f32 = eng.flat.f32.data();
    mgv.n_groups = ctl->n_groups;
    GpuTallyView tvv {};
    tvv.n_tallies = 0;
    tvv.i32 = eng.flat.i32.data();
    tvv.f32 = eng.flat.f32.data();
    std::vector<GpuSourceSite> host_fission(3 * (size_t)n);
    std::vector<uint32_t> host_prog(n);
    std::vector<float> host_red(eng.n_red_slots * GPU_RED_WIDTH, 0.f);
    uint32_t host_ctr[GPU_CTR_COUNT] = {};
    GpuBanks hb;
    hb.source = src;
    hb.fission = host_fission.data();
    hb.counters = host_ctr;
    hb.progeny = host_prog.data();
    hb.red_slots = host_red.data();
    for (int64_t i = 0; i < n; ++i)
      gpu_run_particle((uint32_gpu)i, *ctl, geom, mgv, tvv, hb);
    std::fprintf(stderr,
      "[gpu-debug] host replay: lost=%u (init %u advance %u lattice %u "
      "reflect %u)\n",
      host_ctr[GPU_CTR_LOST], host_ctr[GPU_CTR_LOST_INIT],
      host_ctr[GPU_CTR_LOST_ADVANCE], host_ctr[GPU_CTR_LOST_LATTICE],
      host_ctr[GPU_CTR_LOST_REFLECT]);
  }

  // ---- dispatch ----
  char err[1024];
  if (omg_metal_dispatch(
        eng.ctx, "openmc_transport", (unsigned)n, err, sizeof(err))) {
    fatal_error(fmt::format("GPU transport dispatch failed: {}", err));
  }
  eng.gpu_seconds += omg_metal_last_time(eng.ctx);

  // ---- counters ----
  auto* ctr =
    static_cast<uint32_t*>(omg_metal_contents(eng.ctx, OMG_SLOT_COUNTERS));
  uint32_t n_sites = std::min(ctr[GPU_CTR_FISSION_BANK], ctl->fission_bank_cap);
  uint32_t n_lost = ctr[GPU_CTR_LOST];
  if (n_lost > 0) {
    eng.lost_total += n_lost;
    warning(fmt::format("GPU transport lost {} particles this generation "
                        "({} total; init {} advance {} lattice {} reflect {})",
      n_lost, eng.lost_total, ctr[GPU_CTR_LOST_INIT],
      ctr[GPU_CTR_LOST_ADVANCE], ctr[GPU_CTR_LOST_LATTICE],
      ctr[GPU_CTR_LOST_REFLECT]));
  }
  if (ctr[GPU_CTR_MAX_EVENT_HIT] > 0) {
    warning(fmt::format("{} particles hit the max-event cap on the GPU",
      ctr[GPU_CTR_MAX_EVENT_HIT]));
  }

  // ---- fission bank + progeny bookkeeping (feeds upstream sort/sync) ----
  auto* fb = static_cast<GpuSourceSite*>(
    omg_metal_contents(eng.ctx, OMG_SLOT_FISSION));
  simulation::fission_bank.resize(n_sites);
  for (uint32_t i = 0; i < n_sites; ++i) {
    const GpuSourceSite& g = fb[i];
    SourceSite s;
    s.r = {g.r[0], g.r[1], g.r[2]};
    s.u = {g.u[0], g.u[1], g.u[2]};
    s.E = g.E;
    s.time = g.time;
    s.wgt = g.wgt;
    s.delayed_group = g.delayed_group;
    s.surf_id = 0;
    s.particle = ParticleType::neutron();
    s.parent_id = g.parent_id;
    s.progeny_id = g.progeny_id;
    simulation::fission_bank[i] = s;
  }
  auto* prog =
    static_cast<uint32_t*>(omg_metal_contents(eng.ctx, OMG_SLOT_PROGENY));
  for (int64_t i = 0; i < n; ++i)
    simulation::progeny_per_particle[i] = prog[i];

  // ---- keff estimator reduction (fp32 slots -> fp64 globals) ----
  auto* red =
    static_cast<float*>(omg_metal_contents(eng.ctx, OMG_SLOT_REDSLOTS));
  double sums[GPU_RED_WIDTH] = {};
  for (uint32_t s = 0; s < eng.n_red_slots; ++s)
    for (int k = 0; k < GPU_RED_WIDTH; ++k)
      sums[k] += red[s * GPU_RED_WIDTH + k];
  global_tally_tracklength += sums[GPU_RED_K_TRACKLENGTH];
  global_tally_collision += sums[GPU_RED_K_COLLISION];
  global_tally_absorption += sums[GPU_RED_K_ABSORPTION];
  global_tally_leakage += sums[GPU_RED_LEAKAGE];

  // ---- tally results (fp32 batch bins -> fp64 running VALUE) ----
  if (ctl->n_tallies > 0) {
    auto* acc =
      static_cast<float*>(omg_metal_contents(eng.ctx, OMG_SLOT_TACCUM));
    for (size_t ti = 0; ti < eng.flat.tallies.size(); ++ti) {
      const GpuTallyDesc& td = eng.flat.tallies[ti];
      int32_t host_idx = eng.flat.tally_host_index[ti];
      if (!model::tallies[host_idx]->active_)
        continue;
      double* results;
      size_t shape[3];
      if (openmc_tally_results(host_idx, &results, shape))
        continue;
      for (uint32_t b = 0; b < td.n_filter_bins; ++b) {
        for (uint32_t s = 0; s < td.n_scores; ++s) {
          results[(b * td.n_scores + s) * 3 + 0] +=
            acc[td.accum_off + b * td.n_scores + s];
        }
      }
    }
  }
}

void finalize()
{
  if (eng.ctx) {
    if (eng.active) {
      write_message(
        fmt::format("GPU transport device time: {:.3f} s", eng.gpu_seconds),
        6);
    }
    omg_metal_destroy(eng.ctx);
    eng.ctx = nullptr;
  }
  eng.active = false;
  eng.gpu_seconds = 0.0;
  eng.lost_total = 0;
}

} // namespace gpu
} // namespace openmc
